### PR TITLE
Install schemas

### PR DESCRIPTION
**Pull request by amolenaar**
This is the Flathub counterpart of https://github.com/gaphor/gaphor/pull/3039.

### CODE REVIEW

**Comment by danyeaw** [comment]
@amolenaar Do we still need to get this merged?

**Comment by amolenaar** [comment]
Not if the schemas have been installed properly in 2.24. It no longer works with `poe install-schemas`.

**Comment by amolenaar** [comment]
I think we still want this, so we can get rid of the copy of the schema in this repo.

**Comment by amolenaar** [comment]
@danyeaw I think it's ready.

**Review by danyeaw — APPROVED** [review]
Thanks @amolenaar!

**Pull request merged**
