### PR TITLE
Add Hungarian Translation of the desktop file

### PR DESCRIPTION
**Pull request by ovari**
* Added `hu` locale
* Sorted locales alphabetically

### CODE REVIEW

**Comment by danyeaw** [comment]
@flathubbot rebuild

**Comment by danyeaw** [comment]
@flathubbot build

**Comment by danyeaw** [comment]
bot, build

**Review by danyeaw — APPROVED** [review]
Thanks @ovari!

**Comment by ovari** [comment]
Can we delete https://github.com/ovari/org.gaphor.Gaphor/settings?confirm_delete=yes ?

**Comment by danyeaw** [comment]
@ovari Yes, you can delete your branch.

**Pull request merged**
